{% set name = "repo2cli" %}
{% set version = "0.0.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
     path: .

build:
  number: 0
  script: python setup.py install
  noarch: python

requirements:
  host:
    - setuptools

  run:
    - cookiecutter
    - pyyaml
    - click
    - setuptools

about:
  home: https://docs.terradue.com/ellip/
  license: EUPL License
  summary: "Notebook tools"




